// actual api
// https://groww.in/v1/api/portfolio/v2/dashboard?actTime=1649528901849&list_tracked=true
export default {
  invested_amount: 2829728.0958195003,
  portfolio_value: 3559696.35,
  portfolio_delta: {
    value_delta: {
      one_day_return: 0.7020866496549817,
      return_date: '2022-04-09',
      return_value: 24817.90961149989,
    },
    xirr_delta: {
      xirr: 9.0,
      xirr_date: '2022-04-09',
    },
  },
  systematic_plan_details: {
    sipCount: 0,
    swpCount: 0,
    stpCount: 0,
    sipAmount: 0,
    upcomingSipCount: 0,
    upcomingSipDuration: 0,
    stpOrderDtos: null,
    swpOrderDtos: null,
  },
  investments: {
    portfolio_schemes: [
      {
        currentNav: 9.886,
        category: null,
        scheme_code: '149182',
        user_account_id: 'ACC8051920711032',
        amcCode: 'KOTAK_MAHINDRA',
        scheme_name: 'Kotak Multicap Fund Regular   Growth',
        search_id: 'kotak-multicap-fund-regular-growth',
        folio_number: '9322343/11',
        amount_invested_tax: 4999.75,
        amount_invested: 0.0,
        nav: 9.886,
        average_nav: 10.0,
        units: 499.975,
        current_nav_date: '2022-04-08T05:30:00.941',
        current_value: 4942.75,
        xirr: -2.16,
        parsed_snapshot: false,
        plan_type: 'Regular',
        switch_status: 'NA',
        wish_id: null,
        switch_allowed: null,
        absolute_return: -57.0,
        absolute_return_percentage: -1.14,
        purchase_date: null,
        portfolio_source: 'CAS',
        groww_scheme_code: 'INF174KA1HS9',
        is_nfo: null,
        scheme_type: 'Growth',
        day_change: {
          value: 0.08399999999999963,
          percentage: 0.8569679657212775,
        },
        sip_details: {
          numberOfActiveSip: 0,
          has_active_sip: false,
        },
        amount_withdraw: 5004.75,
        redemption_allowed: true,
        scheme_config: {
          primaryAction: 'SWITCH',
          secondaryAction: null,
          sipAllowed: false,
          lumpsumAllowed: false,
          stpAllowed: false,
          swpAllowed: true,
          switchAllowedDirect: false,
          switchAllowedRegular: true,
          redemptionAllowed: true,
          investMoreAllowed: true,
          purchaseRemark: null,
          redeemRemark: null,
          remark: null,
          extraActions: ['DELETE', 'INVEST MORE'],
        },
        folio_type: 'P',
      },
      {
        currentNav: 41.1,
        category: 'Equity',
        scheme_code: '107745',
        user_account_id: 'ACC8051920711032',
        amcCode: 'BIRLA_SUN_LIFE',
        scheme_name: 'Aditya Birla Sun Life Tax Relief 96 Growth',
        search_id: 'birla-sun-life-tax-relief-96-growth',
        folio_number: '1038456436',
        amount_invested_tax: 299792.52504,
        amount_invested: 0.0,
        nav: 41.1,
        average_nav: 30.745043908668325,
        units: 9750.922,
        current_nav_date: '2022-04-08T05:30:00.981',
        current_value: 400762.89,
        xirr: 12.87,
        parsed_snapshot: false,
        plan_type: 'Regular',
        switch_status: 'NA',
        wish_id: null,
        switch_allowed: null,
        absolute_return: 100970.36,
        absolute_return_percentage: 33.68,
        purchase_date: null,
        portfolio_source: 'CAS',
        groww_scheme_code: 'INF209K01108',
        is_nfo: null,
        scheme_type: 'Growth',
        day_change: {
          value: 0.17999999999999972,
          percentage: 0.43988269794721335,
        },
        sip_details: {
          numberOfActiveSip: 0,
          has_active_sip: false,
        },
        amount_withdraw: 202927.8798,
        redemption_allowed: true,
        scheme_config: {
          primaryAction: 'INVEST MORE',
          secondaryAction: null,
          sipAllowed: false,
          lumpsumAllowed: false,
          stpAllowed: true,
          swpAllowed: true,
          switchAllowedDirect: false,
          switchAllowedRegular: false,
          redemptionAllowed: true,
          investMoreAllowed: true,
          purchaseRemark: null,
          redeemRemark: null,
          remark: null,
          extraActions: ['DELETE'],
        },
        folio_type: 'P',
      },
      {
        currentNav: 5168.2672,
        category: 'Debt',
        scheme_code: '100851',
        user_account_id: 'ACC8051920711032',
        amcCode: 'RELIANCE',
        scheme_name: 'Nippon India Liquid Fund Growth',
        search_id: 'reliance-liquid-fund-treasury-plan-growth',
        folio_number: '499198414687',
        amount_invested_tax: 22492.70991,
        amount_invested: 0.0,
        nav: 5168.2672,
        average_nav: 4743.296058625053,
        units: 4.742,
        current_nav_date: '2022-04-08T05:30:00.685',
        current_value: 24507.92,
        xirr: 4.16,
        parsed_snapshot: false,
        plan_type: 'Regular',
        switch_status: 'NA',
        wish_id: null,
        switch_allowed: null,
        absolute_return: 2015.21,
        absolute_return_percentage: 8.96,
        purchase_date: null,
        portfolio_source: 'CAS',
        groww_scheme_code: 'INF204K01UN9',
        is_nfo: null,
        scheme_type: 'Growth',
        day_change: {
          value: -0.34869999999955326,
          percentage: -0.006746487004374871,
        },
        sip_details: {
          numberOfActiveSip: 0,
          has_active_sip: false,
        },
        amount_withdraw: 22848.45,
        redemption_allowed: true,
        scheme_config: {
          primaryAction: 'SWITCH',
          secondaryAction: null,
          sipAllowed: false,
          lumpsumAllowed: false,
          stpAllowed: true,
          swpAllowed: true,
          switchAllowedDirect: false,
          switchAllowedRegular: true,
          redemptionAllowed: true,
          investMoreAllowed: true,
          purchaseRemark: null,
          redeemRemark: null,
          remark: null,
          extraActions: ['DELETE', 'INVEST MORE'],
        },
        folio_type: 'P',
      },
      {
        currentNav: 43.59,
        category: 'Equity',
        scheme_code: '125305',
        user_account_id: 'ACC8051920711032',
        amcCode: 'DHFL_PRAMERICA',
        scheme_name: 'PGIM India Midcap Opportunities Fund Regular Growth',
        search_id: 'dhfl-pramerica-midcap-opportunities-fund-regular-growth',
        folio_number: '9109825245',
        amount_invested_tax: 53697.30718999999,
        amount_invested: 0.0,
        nav: 43.59,
        average_nav: 43.79913962593495,
        units: 1225.99,
        current_nav_date: '2022-04-08T05:30:00.367',
        current_value: 53440.9,
        xirr: -1.36,
        parsed_snapshot: false,
        plan_type: 'Regular',
        switch_status: 'NA',
        wish_id: null,
        switch_allowed: null,
        absolute_return: -256.41,
        absolute_return_percentage: -0.48,
        purchase_date: null,
        portfolio_source: 'CAS',
        groww_scheme_code: 'INF663L01DZ4',
        is_nfo: null,
        scheme_type: 'Growth',
        day_change: {
          value: 0.5200000000000031,
          percentage: 1.2073368934293083,
        },
        sip_details: {
          numberOfActiveSip: 0,
          has_active_sip: false,
        },
        amount_withdraw: 17659.2,
        redemption_allowed: true,
        scheme_config: {
          primaryAction: 'SWITCH',
          secondaryAction: null,
          sipAllowed: false,
          lumpsumAllowed: false,
          stpAllowed: true,
          swpAllowed: true,
          switchAllowedDirect: false,
          switchAllowedRegular: true,
          redemptionAllowed: true,
          investMoreAllowed: true,
          purchaseRemark: null,
          redeemRemark: null,
          remark: null,
          extraActions: ['DELETE', 'INVEST MORE'],
        },
        folio_type: 'P',
      },
      {
        currentNav: 79.3064,
        category: 'Equity',
        scheme_code: '103196',
        user_account_id: 'ACC8051920711032',
        amcCode: 'RELIANCE',
        scheme_name: 'Nippon India Tax Saver (ELSS) Fund Growth',
        search_id: 'reliance-tax-saver-elss-fund-growth',
        folio_number: '406198722706',
        amount_invested_tax: 149992.5388842,
        amount_invested: 0.0,
        nav: 79.3064,
        average_nav: 80.2442,
        units: 1869.201,
        current_nav_date: '2022-04-08T05:30:00.78',
        current_value: 148239.6,
        xirr: -2.78,
        parsed_snapshot: false,
        plan_type: 'Regular',
        switch_status: 'NA',
        wish_id: null,
        switch_allowed: null,
        absolute_return: -1752.94,
        absolute_return_percentage: -1.17,
        purchase_date: null,
        portfolio_source: 'CAS',
        groww_scheme_code: 'INF204K01GK4',
        is_nfo: null,
        scheme_type: 'Growth',
        day_change: {
          value: 0.6332999999999913,
          percentage: 0.8049765421725993,
        },
        sip_details: {
          numberOfActiveSip: 0,
          has_active_sip: false,
        },
        amount_withdraw: 0.0,
        redemption_allowed: true,
        scheme_config: {
          primaryAction: 'INVEST MORE',
          secondaryAction: null,
          sipAllowed: false,
          lumpsumAllowed: false,
          stpAllowed: true,
          swpAllowed: true,
          switchAllowedDirect: false,
          switchAllowedRegular: false,
          redemptionAllowed: false,
          investMoreAllowed: true,
          purchaseRemark: null,
          redeemRemark: 'ELSS Redeem not allowed',
          remark: null,
          extraActions: ['DELETE'],
        },
        folio_type: 'P',
      },
      {
        currentNav: 30.86,
        category: 'Others',
        scheme_code: '138523',
        user_account_id: 'ACC8051920711032',
        amcCode: 'DHFL_PRAMERICA',
        scheme_name: 'PGIM India Global Equity Opportunities Fund Growth',
        search_id: 'dhfl-pramerica-global-agribusiness-offshore-fund-growth',
        folio_number: '9104814351',
        amount_invested_tax: 24898.75152,
        amount_invested: 0.0,
        nav: 30.86,
        average_nav: 35.24,
        units: 706.548,
        current_nav_date: '2022-04-08T05:30:00.795',
        current_value: 21804.07,
        xirr: -9.89,
        parsed_snapshot: false,
        plan_type: 'Regular',
        switch_status: 'NA',
        wish_id: null,
        switch_allowed: null,
        absolute_return: -3094.68,
        absolute_return_percentage: -12.43,
        purchase_date: null,
        portfolio_source: 'CAS',
        groww_scheme_code: 'INF223J01AU8',
        is_nfo: null,
        scheme_type: 'Growth',
        day_change: {
          value: -0.2699999999999996,
          percentage: -0.8673305493093466,
        },
        sip_details: {
          numberOfActiveSip: 0,
          has_active_sip: false,
        },
        amount_withdraw: 22447.03,
        redemption_allowed: true,
        scheme_config: {
          primaryAction: 'SWITCH',
          secondaryAction: null,
          sipAllowed: false,
          lumpsumAllowed: false,
          stpAllowed: true,
          swpAllowed: true,
          switchAllowedDirect: false,
          switchAllowedRegular: true,
          redemptionAllowed: true,
          investMoreAllowed: true,
          purchaseRemark: null,
          redeemRemark: null,
          remark: null,
          extraActions: ['DELETE', 'INVEST MORE'],
        },
        folio_type: 'P',
      },
      {
        currentNav: 1105.84,
        category: 'Hybrid',
        scheme_code: '103155',
        user_account_id: 'ACC8051920711032',
        amcCode: 'BIRLA_SUN_LIFE',
        scheme_name: "Aditya Birla Sun Life Equity Hybrid '95 Fund Growth",
        search_id: 'birla-sun-life-balanced-95-growth',
        folio_number: '1037409491',
        amount_invested_tax: 4950.13927,
        amount_invested: 0.0,
        nav: 1105.84,
        average_nav: 749.4533338380014,
        units: 6.605,
        current_nav_date: '2022-04-08T05:30:00.654',
        current_value: 7304.07,
        xirr: 11.11,
        parsed_snapshot: false,
        plan_type: 'Regular',
        switch_status: 'NA',
        wish_id: null,
        switch_allowed: null,
        absolute_return: 2353.93,
        absolute_return_percentage: 47.55,
        purchase_date: null,
        portfolio_source: 'CAS',
        groww_scheme_code: 'INF209K01BT5',
        is_nfo: null,
        scheme_type: 'Growth',
        day_change: {
          value: 5.839999999999918,
          percentage: 0.5309090909090834,
        },
        sip_details: {
          numberOfActiveSip: 0,
          has_active_sip: false,
        },
        amount_withdraw: 7046.74,
        redemption_allowed: true,
        scheme_config: {
          primaryAction: 'SWITCH',
          secondaryAction: null,
          sipAllowed: false,
          lumpsumAllowed: false,
          stpAllowed: true,
          swpAllowed: true,
          switchAllowedDirect: false,
          switchAllowedRegular: true,
          redemptionAllowed: true,
          investMoreAllowed: true,
          purchaseRemark: null,
          redeemRemark: null,
          remark: null,
          extraActions: ['DELETE', 'INVEST MORE'],
        },
        folio_type: 'P',
      },
      {
        currentNav: 1163.15,
        category: 'Equity',
        scheme_code: '103166',
        user_account_id: 'ACC8051920711032',
        amcCode: 'BIRLA_SUN_LIFE',
        scheme_name: 'Aditya Birla Sun Life Flexi Cap Fund Growth',
        search_id: 'birla-sun-life-equity-fund-growth',
        folio_number: '1037409491',
        amount_invested_tax: 94722.91167,
        amount_invested: 0.0,
        nav: 1163.15,
        average_nav: 791.5607747396922,
        units: 119.666,
        current_nav_date: '2022-04-08T05:30:00.529',
        current_value: 139189.51,
        xirr: 23.06,
        parsed_snapshot: false,
        plan_type: 'Regular',
        switch_status: 'NA',
        wish_id: null,
        switch_allowed: null,
        absolute_return: 44466.6,
        absolute_return_percentage: 46.94,
        purchase_date: null,
        portfolio_source: 'CAS',
        groww_scheme_code: 'INF209K01AJ8',
        is_nfo: null,
        scheme_type: 'Growth',
        day_change: {
          value: 8.840000000000146,
          percentage: 0.7658254714938054,
        },
        sip_details: {
          numberOfActiveSip: 0,
          has_active_sip: false,
        },
        amount_withdraw: 156724.18,
        redemption_allowed: true,
        scheme_config: {
          primaryAction: 'SWITCH',
          secondaryAction: null,
          sipAllowed: false,
          lumpsumAllowed: false,
          stpAllowed: true,
          swpAllowed: true,
          switchAllowedDirect: false,
          switchAllowedRegular: true,
          redemptionAllowed: true,
          investMoreAllowed: true,
          purchaseRemark: null,
          redeemRemark: null,
          remark: null,
          extraActions: ['DELETE', 'INVEST MORE'],
        },
        folio_type: 'P',
      },
      {
        currentNav: 74.1352,
        category: 'Equity',
        scheme_code: '108167',
        user_account_id: 'ACC8051920711032',
        amcCode: 'BIRLA_SUN_LIFE',
        scheme_name: 'Aditya Birla Sun Life Pure Value Fund Growth',
        search_id: 'birla-sun-life-pure-value-fund-growth',
        folio_number: '1037409491',
        amount_invested_tax: 124799.9907887,
        amount_invested: 0.0,
        nav: 74.1352,
        average_nav: 59.50391032678997,
        units: 2097.341,
        current_nav_date: '2022-04-08T05:30:00.9',
        current_value: 155486.79,
        xirr: 5.85,
        parsed_snapshot: false,
        plan_type: 'Regular',
        switch_status: 'NA',
        wish_id: null,
        switch_allowed: null,
        absolute_return: 30686.8,
        absolute_return_percentage: 24.59,
        purchase_date: null,
        portfolio_source: 'CAS',
        groww_scheme_code: 'INF209K01LF3',
        is_nfo: null,
        scheme_type: 'Growth',
        day_change: {
          value: 1.0707999999999913,
          percentage: 1.4655564132463843,
        },
        sip_details: {
          numberOfActiveSip: 0,
          has_active_sip: false,
        },
        amount_withdraw: 154241.39,
        redemption_allowed: true,
        scheme_config: {
          primaryAction: 'SWITCH',
          secondaryAction: null,
          sipAllowed: false,
          lumpsumAllowed: false,
          stpAllowed: true,
          swpAllowed: true,
          switchAllowedDirect: false,
          switchAllowedRegular: true,
          redemptionAllowed: true,
          investMoreAllowed: true,
          purchaseRemark: null,
          redeemRemark: null,
          remark: null,
          extraActions: ['DELETE', 'INVEST MORE'],
        },
        folio_type: 'P',
      },
      {
        currentNav: 25.0888,
        category: 'Hybrid',
        scheme_code: '101143',
        user_account_id: 'ACC8051920711032',
        amcCode: 'ICICI_PRUDENTIAL',
        scheme_name: 'ICICI Prudential Multi Asset Fund IDCW',
        search_id: 'icici-prudential-dynamic-plan-dividend',
        folio_number: '13767030/55',
        amount_invested_tax: 129799.12020259998,
        amount_invested: 0.0,
        nav: 25.0888,
        average_nav: 20.49967753103242,
        units: 6331.764,
        current_nav_date: '2022-04-08T05:30:00.291',
        current_value: 158856.36,
        xirr: 8.47,
        parsed_snapshot: false,
        plan_type: 'Regular',
        switch_status: 'NA',
        wish_id: null,
        switch_allowed: null,
        absolute_return: 29057.24,
        absolute_return_percentage: 22.39,
        purchase_date: null,
        portfolio_source: 'CAS',
        groww_scheme_code: 'INF109K01779',
        is_nfo: null,
        scheme_type: 'Dividend',
        day_change: {
          value: 0.0630999999999986,
          percentage: 0.2521407992583568,
        },
        sip_details: {
          numberOfActiveSip: 0,
          has_active_sip: false,
        },
        amount_withdraw: 0.0,
        redemption_allowed: true,
        scheme_config: {
          primaryAction: 'SWITCH',
          secondaryAction: null,
          sipAllowed: false,
          lumpsumAllowed: false,
          stpAllowed: true,
          swpAllowed: true,
          switchAllowedDirect: false,
          switchAllowedRegular: true,
          redemptionAllowed: true,
          investMoreAllowed: true,
          purchaseRemark: null,
          redeemRemark: null,
          remark: null,
          extraActions: ['DELETE', 'INVEST MORE'],
        },
        folio_type: 'P',
      },
      {
        currentNav: 89.4179,
        category: 'Equity',
        scheme_code: '113177',
        user_account_id: 'ACC8051920711032',
        amcCode: 'RELIANCE',
        scheme_name: 'Nippon India Small Cap Fund   Growth',
        search_id: 'reliance-small-cap-fund-growth',
        folio_number: '406198722706',
        amount_invested_tax: 95594.07844589998,
        amount_invested: 0.0,
        nav: 89.4179,
        average_nav: 57.280584661214675,
        units: 1668.874,
        current_nav_date: '2022-04-08T05:30:00.27',
        current_value: 149227.21,
        xirr: 54.58,
        parsed_snapshot: false,
        plan_type: 'Regular',
        switch_status: 'NA',
        wish_id: null,
        switch_allowed: null,
        absolute_return: 53633.13,
        absolute_return_percentage: 56.11,
        purchase_date: null,
        portfolio_source: 'CAS',
        groww_scheme_code: 'INF204K01HY3',
        is_nfo: null,
        scheme_type: 'Growth',
        day_change: {
          value: 0.9605999999999995,
          percentage: 1.0859476832324741,
        },
        sip_details: {
          numberOfActiveSip: 0,
          has_active_sip: false,
        },
        amount_withdraw: 157884.4,
        redemption_allowed: true,
        scheme_config: {
          primaryAction: 'SWITCH',
          secondaryAction: null,
          sipAllowed: false,
          lumpsumAllowed: false,
          stpAllowed: true,
          swpAllowed: true,
          switchAllowedDirect: false,
          switchAllowedRegular: true,
          redemptionAllowed: true,
          investMoreAllowed: true,
          purchaseRemark: null,
          redeemRemark: null,
          remark: null,
          extraActions: ['DELETE', 'INVEST MORE'],
        },
        folio_type: 'P',
      },
      {
        currentNav: 162.07,
        category: 'Hybrid',
        scheme_code: '103154',
        user_account_id: 'ACC8051920711032',
        amcCode: 'BIRLA_SUN_LIFE',
        scheme_name: "Aditya Birla Sun Life Equity Hybrid '95 Fund IDCW",
        search_id: 'birla-sun-life-balanced-95-dividend',
        folio_number: '1037409491',
        amount_invested_tax: 669457.0673499999,
        amount_invested: 0.0,
        nav: 162.07,
        average_nav: 140.57168940840404,
        units: 4762.389,
        current_nav_date: '2022-04-08T05:30:00.733',
        current_value: 771840.39,
        xirr: 4.06,
        parsed_snapshot: false,
        plan_type: 'Regular',
        switch_status: 'NA',
        wish_id: null,
        switch_allowed: null,
        absolute_return: 102383.32,
        absolute_return_percentage: 15.29,
        purchase_date: null,
        portfolio_source: 'CAS',
        groww_scheme_code: 'INF209K01BS7',
        is_nfo: null,
        scheme_type: 'Dividend',
        day_change: {
          value: 0.8599999999999852,
          percentage: 0.5334656659016098,
        },
        sip_details: {
          numberOfActiveSip: 0,
          has_active_sip: false,
        },
        amount_withdraw: 0.0,
        redemption_allowed: true,
        scheme_config: {
          primaryAction: 'SWITCH',
          secondaryAction: null,
          sipAllowed: false,
          lumpsumAllowed: false,
          stpAllowed: true,
          swpAllowed: true,
          switchAllowedDirect: false,
          switchAllowedRegular: true,
          redemptionAllowed: true,
          investMoreAllowed: true,
          purchaseRemark: null,
          redeemRemark: null,
          remark: null,
          extraActions: ['DELETE', 'INVEST MORE'],
        },
        folio_type: 'P',
      },
      {
        currentNav: 162.07,
        category: 'Hybrid',
        scheme_code: '103154',
        user_account_id: 'ACC8051920711032',
        amcCode: 'BIRLA_SUN_LIFE',
        scheme_name: "Aditya Birla Sun Life Equity Hybrid '95 Fund IDCW",
        search_id: 'birla-sun-life-balanced-95-dividend',
        folio_number: '1037481239',
        amount_invested_tax: 99899.93817,
        amount_invested: 0.0,
        nav: 162.07,
        average_nav: 140.13,
        units: 712.909,
        current_nav_date: '2022-04-08T05:30:00.733',
        current_value: 115541.16,
        xirr: 3.85,
        parsed_snapshot: false,
        plan_type: 'Regular',
        switch_status: 'NA',
        wish_id: null,
        switch_allowed: null,
        absolute_return: 15641.22,
        absolute_return_percentage: 15.66,
        purchase_date: null,
        portfolio_source: 'CAS',
        groww_scheme_code: 'INF209K01BS7',
        is_nfo: null,
        scheme_type: 'Dividend',
        day_change: {
          value: 0.8599999999999852,
          percentage: 0.5334656659016098,
        },
        sip_details: {
          numberOfActiveSip: 0,
          has_active_sip: false,
        },
        amount_withdraw: 0.0,
        redemption_allowed: true,
        scheme_config: {
          primaryAction: 'SWITCH',
          secondaryAction: null,
          sipAllowed: false,
          lumpsumAllowed: false,
          stpAllowed: true,
          swpAllowed: true,
          switchAllowedDirect: false,
          switchAllowedRegular: true,
          redemptionAllowed: true,
          investMoreAllowed: true,
          purchaseRemark: null,
          redeemRemark: null,
          remark: null,
          extraActions: ['DELETE', 'INVEST MORE'],
        },
        folio_type: 'P',
      },
      {
        currentNav: 46.95,
        category: 'Equity',
        scheme_code: '129223',
        user_account_id: 'ACC8051920711032',
        amcCode: 'L&T',
        scheme_name: 'L&T Emerging Businesses Fund Growth',
        search_id: 'lt-emerging-businesses-fund-regular-growth',
        folio_number: '4563629/81',
        amount_invested_tax: 152096.298137,
        amount_invested: 0.0,
        nav: 46.95,
        average_nav: 25.488217342699016,
        units: 5967.318,
        current_nav_date: '2022-04-08T05:30:00.765',
        current_value: 280165.58,
        xirr: 47.88,
        parsed_snapshot: false,
        plan_type: 'Regular',
        switch_status: 'NA',
        wish_id: null,
        switch_allowed: null,
        absolute_return: 128069.28,
        absolute_return_percentage: 84.2,
        purchase_date: null,
        portfolio_source: 'CAS',
        groww_scheme_code: 'INF917K01QC7',
        is_nfo: null,
        scheme_type: 'Growth',
        day_change: {
          value: 0.3950000000000031,
          percentage: 0.8484588121576696,
        },
        sip_details: {
          numberOfActiveSip: 0,
          has_active_sip: false,
        },
        amount_withdraw: 294531.02,
        redemption_allowed: false,
        scheme_config: {
          primaryAction: 'SWITCH',
          secondaryAction: null,
          sipAllowed: false,
          lumpsumAllowed: false,
          stpAllowed: true,
          swpAllowed: true,
          switchAllowedDirect: false,
          switchAllowedRegular: true,
          redemptionAllowed: true,
          investMoreAllowed: true,
          purchaseRemark: null,
          redeemRemark: null,
          remark: null,
          extraActions: ['DELETE', 'INVEST MORE'],
        },
        folio_type: 'P',
      },
      {
        currentNav: 20.046,
        category: 'Equity',
        scheme_code: '104773',
        user_account_id: 'ACC8051920711032',
        amcCode: 'DSP',
        scheme_name: 'DSP Tax Saver Fund IDCW',
        search_id: 'dsp-blackrock-tax-saver-fund-dividend',
        folio_number: '70014027/01',
        amount_invested_tax: 149900.000768,
        amount_invested: 0.0,
        nav: 20.046,
        average_nav: 15.232,
        units: 9841.124,
        current_nav_date: '2022-04-08T05:30:00.993',
        current_value: 197275.17,
        xirr: 13.05,
        parsed_snapshot: false,
        plan_type: 'Regular',
        switch_status: 'NA',
        wish_id: null,
        switch_allowed: null,
        absolute_return: 47375.17,
        absolute_return_percentage: 31.6,
        purchase_date: null,
        portfolio_source: 'CAS',
        groww_scheme_code: 'INF740K01169',
        is_nfo: null,
        scheme_type: 'Dividend',
        day_change: {
          value: 0.1529999999999987,
          percentage: 0.7691147639873257,
        },
        sip_details: {
          numberOfActiveSip: 0,
          has_active_sip: false,
        },
        amount_withdraw: 0.0,
        redemption_allowed: true,
        scheme_config: {
          primaryAction: 'INVEST MORE',
          secondaryAction: null,
          sipAllowed: false,
          lumpsumAllowed: false,
          stpAllowed: true,
          swpAllowed: true,
          switchAllowedDirect: false,
          switchAllowedRegular: false,
          redemptionAllowed: false,
          investMoreAllowed: true,
          purchaseRemark: null,
          redeemRemark: 'ELSS Redeem not allowed',
          remark: null,
          extraActions: ['DELETE'],
        },
        folio_type: 'P',
      },
      {
        currentNav: 75.209,
        category: 'Equity',
        scheme_code: '130502',
        user_account_id: 'ACC8051920711032',
        amcCode: 'HDFC',
        scheme_name: 'HDFC Small Cap Fund Regular Growth',
        search_id: 'hdfc-small-and-mid-cap-fund-growth',
        folio_number: '14237242/90',
        amount_invested_tax: 145260.45406400002,
        amount_invested: 0.0,
        nav: 75.209,
        average_nav: 44.25180804414079,
        units: 3282.588,
        current_nav_date: '2022-04-08T05:30:00.206',
        current_value: 246880.16,
        xirr: 42.86,
        parsed_snapshot: false,
        plan_type: 'Regular',
        switch_status: 'NA',
        wish_id: null,
        switch_allowed: null,
        absolute_return: 101619.71,
        absolute_return_percentage: 69.96,
        purchase_date: null,
        portfolio_source: 'CAS',
        groww_scheme_code: 'INF179KA1RZ8',
        is_nfo: null,
        scheme_type: 'Growth',
        day_change: {
          value: 0.820999999999998,
          percentage: 1.1036726353712936,
        },
        sip_details: {
          numberOfActiveSip: 0,
          has_active_sip: false,
        },
        amount_withdraw: 265186.38,
        redemption_allowed: true,
        scheme_config: {
          primaryAction: 'SWITCH',
          secondaryAction: null,
          sipAllowed: false,
          lumpsumAllowed: false,
          stpAllowed: true,
          swpAllowed: true,
          switchAllowedDirect: false,
          switchAllowedRegular: true,
          redemptionAllowed: true,
          investMoreAllowed: true,
          purchaseRemark: null,
          redeemRemark: null,
          remark: null,
          extraActions: ['DELETE', 'INVEST MORE'],
        },
        folio_type: 'P',
      },
      {
        currentNav: 66.7086,
        category: 'Equity',
        scheme_code: '119598',
        user_account_id: 'ACC8051920711032',
        amcCode: 'SBI',
        scheme_name: 'SBI Bluechip Direct Plan Growth',
        search_id: 'sbi-bluechip-fund-direct-growth',
        folio_number: '20223805',
        amount_invested_tax: 107497.79630010003,
        amount_invested: 0.0,
        nav: 66.7086,
        average_nav: 45.09803519568965,
        units: 2383.647,
        current_nav_date: '2022-04-08T05:30:00.831',
        current_value: 159009.75,
        xirr: 20.4,
        parsed_snapshot: false,
        plan_type: 'Direct',
        switch_status: 'NA',
        wish_id: null,
        switch_allowed: null,
        absolute_return: 51511.95,
        absolute_return_percentage: 47.92,
        purchase_date: null,
        portfolio_source: 'CAS',
        groww_scheme_code: 'INF200K01QX4',
        is_nfo: null,
        scheme_type: 'Growth',
        day_change: {
          value: 0.5640000000000072,
          percentage: 0.8526773160620931,
        },
        sip_details: {
          numberOfActiveSip: 0,
          has_active_sip: false,
        },
        amount_withdraw: 151850.95,
        redemption_allowed: true,
        scheme_config: {
          primaryAction: 'INVEST MORE',
          secondaryAction: null,
          sipAllowed: true,
          lumpsumAllowed: true,
          stpAllowed: true,
          swpAllowed: true,
          switchAllowedDirect: true,
          switchAllowedRegular: false,
          redemptionAllowed: true,
          investMoreAllowed: true,
          purchaseRemark: null,
          redeemRemark: null,
          remark: null,
          extraActions: ['DELETE', 'SWITCH'],
        },
        folio_type: 'P',
      },
      {
        currentNav: 29.843,
        category: 'Hybrid',
        scheme_code: '100120',
        user_account_id: 'ACC8051920711032',
        amcCode: 'HDFC',
        scheme_name: 'HDFC Balanced Advantage Fund IDCW Monthly',
        search_id: 'hdfc-growth-fund-dividend',
        folio_number: '14237242/90',
        amount_invested_tax: 458476.7879489999,
        amount_invested: 0.0,
        nav: 29.843,
        average_nav: 29.81096149275625,
        units: 15379.47,
        current_nav_date: '2022-04-08T05:30:00.853',
        current_value: 458969.52,
        xirr: 0.03,
        parsed_snapshot: false,
        plan_type: 'Regular',
        switch_status: 'NA',
        wish_id: null,
        switch_allowed: null,
        absolute_return: 492.73,
        absolute_return_percentage: 0.11,
        purchase_date: null,
        portfolio_source: 'CAS',
        groww_scheme_code: 'INF179K01822',
        is_nfo: null,
        scheme_type: 'Dividend',
        day_change: {
          value: 0.19399999999999906,
          percentage: 0.6543222368376642,
        },
        sip_details: {
          numberOfActiveSip: 0,
          has_active_sip: false,
        },
        amount_withdraw: 0.0,
        redemption_allowed: true,
        scheme_config: {
          primaryAction: 'SWITCH',
          secondaryAction: null,
          sipAllowed: false,
          lumpsumAllowed: false,
          stpAllowed: false,
          swpAllowed: false,
          switchAllowedDirect: false,
          switchAllowedRegular: true,
          redemptionAllowed: false,
          investMoreAllowed: true,
          purchaseRemark: null,
          redeemRemark: null,
          remark: null,
          extraActions: ['DELETE', 'INVEST MORE'],
        },
        folio_type: 'P',
      },
      {
        currentNav: 43.93,
        category: 'Equity',
        scheme_code: '117560',
        user_account_id: 'ACC8051920711032',
        amcCode: 'AXIS',
        scheme_name: 'Axis Focused 25 Fund Growth',
        search_id: 'axis-focused-25-fund-growth',
        folio_number: '90639801586',
        amount_invested_tax: 41399.93016,
        amount_invested: 0.0,
        nav: 43.93,
        average_nav: 27.451004290718565,
        units: 1508.139,
        current_nav_date: '2022-04-08T05:30:00.774',
        current_value: 66252.55,
        xirr: 14.95,
        parsed_snapshot: false,
        plan_type: 'Regular',
        switch_status: 'NA',
        wish_id: null,
        switch_allowed: null,
        absolute_return: 24852.62,
        absolute_return_percentage: 60.03,
        purchase_date: null,
        portfolio_source: 'CAS',
        groww_scheme_code: 'INF846K01CH7',
        is_nfo: null,
        scheme_type: 'Growth',
        day_change: {
          value: 0.29999999999999716,
          percentage: 0.6876002750401035,
        },
        sip_details: {
          numberOfActiveSip: 0,
          has_active_sip: false,
        },
        amount_withdraw: 67715.44,
        redemption_allowed: false,
        scheme_config: {
          primaryAction: 'SWITCH',
          secondaryAction: null,
          sipAllowed: false,
          lumpsumAllowed: false,
          stpAllowed: true,
          swpAllowed: true,
          switchAllowedDirect: false,
          switchAllowedRegular: true,
          redemptionAllowed: true,
          investMoreAllowed: true,
          purchaseRemark: null,
          redeemRemark: null,
          remark: null,
          extraActions: ['DELETE', 'INVEST MORE'],
        },
        folio_type: 'P',
      },
    ],
  },
}
